/**
 * Booking domain types.
 *
 * These are application-level types used across components,
 * hooks, stores, and server actions.
 *
 * Database row types will be generated by the Supabase CLI in Phase 2
 * and imported from `@/types/database.ts`. These types represent the
 * shape of data as the application consumes it — after any joins,
 * transformations, or computed fields are applied.
 */

import type { AppointmentStatus } from "@/lib/utils/format";

/* ── Service ─────────────────────────────────────────────────────────────── */

export interface Service {
  id: string;
  name: string;
  slug: string;
  category: string | null;
  description: string | null;
  durationMin: number;
  price: number;
  isVisible: boolean;
  displayOrder: number;
}

/* ── Employee ────────────────────────────────────────────────────────────── */

export interface Employee {
  id: string;
  name: string;
  slug: string;
  bio: string | null;
  avatarUrl: string | null;
  colorTag: string;
  specialties: string[];
  isActive: boolean;
  displayOrder: number;
}

/* ── Time Slot ───────────────────────────────────────────────────────────── */

export interface TimeSlot {
  startAt: Date;
  endAt: Date;
  label: string;
}

/* ── Booking Wizard State ────────────────────────────────────────────────── */

export type BookingStep = 1 | 2 | 3 | 4 | 5;

export interface BookingWizardState {
  currentStep: BookingStep;

  // Step 1
  selectedService: Service | null;

  // Step 2
  selectedEmployee: Employee | null;
  anyEmployee: boolean;

  // Step 3
  selectedDate: string | null;   // "YYYY-MM-DD" local date string
  selectedSlot: TimeSlot | null;

  // Step 4
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  customerNote: string;
}

/* ── Booking Confirmation ────────────────────────────────────────────────── */

export interface BookingConfirmation {
  id: string;
  cancelToken: string;
  service: Pick<Service, "id" | "name" | "durationMin" | "price">;
  employee: Pick<Employee, "id" | "name" | "avatarUrl">;
  startAt: Date;
  endAt: Date;
  customer: {
    name: string;
    email: string;
    phone: string;
  };
  status: AppointmentStatus;
}

/* ── Appointment (Admin view) ────────────────────────────────────────────── */

export interface Appointment {
  id: string;
  status: AppointmentStatus;
  startAt: Date;
  endAt: Date;
  priceSnapshot: number;
  customerNote: string | null;
  adminNote: string | null;
  cancelledAt: Date | null;
  cancelledBy: "customer" | "admin" | null;
  createdAt: Date;
  customer: {
    id: string;
    name: string;
    email: string;
    phone: string | null;
  };
  service: Pick<Service, "id" | "name" | "durationMin" | "price">;
  employee: Pick<Employee, "id" | "name" | "avatarUrl" | "colorTag">;
}

/* ── Availability Request ────────────────────────────────────────────────── */

export interface AvailabilityRequest {
  date: string;        // "YYYY-MM-DD"
  serviceId: string;
  employeeId: string | "any";
}

export interface AvailabilityResponse {
  slots: TimeSlot[];
  employeeId: string;
}