/**
 * BarberPro — Supabase Database Types
 *
 * This file is auto-generated by the Supabase CLI.
 * DO NOT edit manually.
 *
 * To regenerate after schema changes, run:
 *   npx supabase gen types typescript --project-id <your-project-ref> > src/types/database.ts
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * Temporary placeholder — keeps TypeScript happy during Phase 1.
 * Replaced with the full generated schema in Phase 2 once the
 * Supabase tables are created.
 * ─────────────────────────────────────────────────────────────────────────────
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}